import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { FaBoxArchive } from "react-icons/fa6";
import {
	IoIosHome,
	IoMdDocument,
	IoMdPeople,
	IoMdSettings,
} from "react-icons/io";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" data-thenes="light">
            <body className={inter.className}>
                <section className="h-screen w-screen flex bg-stone-300">
                    <div className="static w-[120px] cursor-pointer h-screen bg-indigo-500">
                        <div className="h-[20%] flex items-center justify-center border-b text-white hover:bg-white hover:text-indigo-500">
                            <a href="/dashboard">
                                <IoIosHome className="text-2xl ml-6" />
                                <p>Dashboard</p>
                            </a>
                        </div>
                        <div className="h-[20%] flex items-center justify-center border-b py-3 text-white hover:bg-white hover:text-indigo-500">
                            <a href="/">
                                <IoMdDocument className="text-2xl ml-6" />
                                <p>New Order</p>
                            </a>
                        </div>
                        <div className="h-[20%] flex items-center justify-center border-b text-white hover:bg-white hover:text-indigo-500">
                            <a href="/suppliers">
                                <IoMdPeople className="text-2xl ml-6" />
                                <p>Suppliers</p>
                            </a>
                        </div>
                        <div className="h-[20%] flex items-center justify-center border-b text-white hover:bg-white hover:text-indigo-500">
                            <a href="/orders">
                                <FaBoxArchive className="text-xl ml-4" />
                                <p>Orders</p>
                            </a>
                        </div>
                        <div className="h-[20%] flex items-center justify-center border-b text-white hover:bg-white hover:text-indigo-500">
                            <a href="/settings">
                                <IoMdSettings className="text-2xl ml-4" />
                                <p>Settings</p>
                            </a>
                        </div>
                    </div>

                    <div className="static w-[900px] h-full flex-1">
                        {children}
                    </div>
                </section>
            </body>
        </html>
    );
}
